import { sql } from "./dbClient.js";

async function seed() {
await sql`
insert into MOCK_DATA (id, name, email, city, country, created_at) values (1, 'Eula Brislawn', 'ebrislawn0@bing.com', 'Gardēz', 'Afghanistan', '2026-04-03 13:12:32');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (2, 'Hesther Bloor', 'hbloor1@pinterest.com', 'Shibirghān', 'Afghanistan', '2026-02-28 06:14:02');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (3, 'Barbra Tuther', 'btuther2@goodreads.com', 'Dowlatyār', 'Afghanistan', '2025-12-05 11:14:23');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (4, 'Rhona Sictornes', 'rsictornes3@nifty.com', 'Markaz-e Woluswalī-ye Āchīn', 'Afghanistan', '2025-11-05 05:38:00');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (5, 'Kalinda Cristoferi', 'kcristoferi4@ask.com', 'Nūsay', 'Afghanistan', '2026-02-10 09:50:02');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (6, 'Harlin Ghiraldi', 'hghiraldi5@istockphoto.com', 'Kabul', 'Afghanistan', '2026-09-13 07:46:43');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (7, 'Nelly Gilmour', 'ngilmour6@youku.com', 'Ashkāsham', 'Afghanistan', '2026-04-10 00:34:57');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (8, 'Pavia Duffree', 'pduffree7@microsoft.com', 'Bāgh-e Maīdān', 'Afghanistan', '2025-10-27 02:20:44');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (9, 'Gianni Gandy', 'ggandy8@is.gd', 'Fayzabad', 'Afghanistan', '2026-06-14 00:01:27');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (10, 'Hans Rabbatts', 'hrabbatts9@blog.com', 'Qarāwul', 'Afghanistan', '2026-02-05 17:36:57');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (11, 'Clemence Bugge', 'cbuggea@google.com.hk', 'Ghormach', 'Afghanistan', '2025-11-04 21:56:41');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (12, 'Mala Verbrugghen', 'mverbrugghenb@oakley.com', 'Khafizan', 'Afghanistan', '2026-01-21 04:49:54');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (13, 'Elianore Cars', 'ecarsc@gravatar.com', 'Gardēz', 'Afghanistan', '2026-03-01 03:39:23');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (14, 'Amos Paullin', 'apaullind@wsj.com', 'Balkh', 'Afghanistan', '2026-08-28 05:01:12');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (15, 'Ferdie Nunes Nabarro', 'fnunese@disqus.com', 'Dasht-e Archī', 'Afghanistan', '2026-03-31 03:49:49');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (16, 'Nigel Morales', 'nmoralesf@jalbum.net', 'Fayzabad', 'Afghanistan', '2026-06-08 22:35:36');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (17, 'Darbee McLoughlin', 'dmcloughling@dedecms.com', 'Khulm', 'Afghanistan', '2026-07-27 09:43:02');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (18, 'Jackelyn Cano', 'jcanoh@smugmug.com', 'Būrkah', 'Afghanistan', '2026-08-04 20:28:45');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (19, 'Dave Bishell', 'dbishelli@amazon.de', 'Adraskan', 'Afghanistan', '2026-04-30 04:56:50');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (20, 'Patten Worge', 'pworgej@kickstarter.com', 'Shibirghān', 'Afghanistan', '2026-09-02 18:32:11');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (21, 'Betty Sanbrook', 'bsanbrookk@shareasale.com', 'Dūāb', 'Afghanistan', '2025-10-17 19:36:26');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (22, 'Corbin Newcomen', 'cnewcomenl@scribd.com', 'Andkhōy', 'Afghanistan', '2026-07-25 16:57:35');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (23, 'Larina Colomb', 'lcolombm@columbia.edu', 'Kanḏay', 'Afghanistan', '2026-05-04 12:49:54');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (24, 'Jilleen Gatiss', 'jgatissn@boston.com', 'Kai', 'Afghanistan', '2026-02-16 21:35:29');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (25, 'Marrissa Caistor', 'mcaistoro@bravesites.com', 'Bala Murghab', 'Afghanistan', '2025-11-15 09:04:17');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (26, 'Jorge Von Salzberg', 'jvonp@people.com.cn', 'Khān Neshīn', 'Afghanistan', '2025-11-29 21:34:10');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (27, 'Gabbie Wyne', 'gwyneq@marketwatch.com', 'Cool űrhajó', 'Afghanistan', '2026-01-31 17:22:00');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (28, 'Morena Folca', 'mfolcar@loc.gov', 'Mutā Khān', 'Afghanistan', '2026-04-05 05:42:23');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (29, 'Nicolle Slocket', 'nslockets@archive.org', 'Kishk-e Nakhūd', 'Afghanistan', '2026-06-09 06:17:50');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (30, 'Nert Goves', 'ngovest@mit.edu', 'Qal‘ah-ye Kūf', 'Afghanistan', '2026-07-15 12:57:00');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (31, 'Stephine Malloch', 'smallochu@microsoft.com', 'Khulm', 'Afghanistan', '2026-08-23 21:33:58');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (32, 'Mada Neesam', 'mneesamv@behance.net', 'Baghlān', 'Afghanistan', '2026-07-22 23:34:32');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (33, 'Alden Passo', 'apassow@google.pl', 'Ḩājī Khēl', 'Afghanistan', '2026-04-30 13:19:55');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (34, 'Ellery Joseland', 'ejoselandx@amazon.com', 'Sar Chakān', 'Afghanistan', '2026-07-22 12:50:37');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (35, 'Gladys Nisen', 'gniseny@pen.io', 'Khinjān', 'Afghanistan', '2026-08-05 21:10:08');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (36, 'Mayer Jacombs', 'mjacombsz@craigslist.org', 'Pul-e Sangī', 'Afghanistan', '2026-02-06 06:13:06');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (37, 'Darleen Sidey', 'dsidey10@google.com.hk', 'Sangar Sarāy', 'Afghanistan', '2026-03-22 22:19:10');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (38, 'Boonie McKim', 'bmckim11@nbcnews.com', 'Khulm', 'Afghanistan', '2025-11-08 10:07:46');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (39, 'Keene Elloy', 'kelloy12@webmd.com', 'Kunduz', 'Afghanistan', '2026-03-05 20:12:11');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (40, 'Pooh Joao', 'pjoao13@usda.gov', 'Qarchī Gak', 'Afghanistan', '2026-09-11 03:48:23');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (41, 'Jessica Clemmens', 'jclemmens14@ezinearticles.com', 'Karukh', 'Afghanistan', '2026-07-19 20:44:23');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (42, 'Daloris Blinman', 'dblinman15@issuu.com', 'Qal‘ah-ye Na‘īm', 'Afghanistan', '2025-11-12 20:14:32');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (43, 'Kean Ivashkin', 'kivashkin16@hud.gov', 'Ghormach', 'Afghanistan', '2026-05-02 03:16:43');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (44, 'Hanson Rillstone', 'hrillstone17@bigcartel.com', 'Khafizan', 'Afghanistan', '2026-04-05 05:30:09');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (45, 'Sallyanne Abels', 'sabels18@nymag.com', 'Rū-ye Sang', 'Afghanistan', '2026-04-26 05:11:06');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (46, 'Cammy Abrahmer', 'cabrahmer19@sina.com.cn', 'Khōshī', 'Afghanistan', '2026-05-06 07:37:21');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (47, 'Jaime Boorman', 'jboorman1a@home.pl', 'Kunduz', 'Afghanistan', '2026-04-12 12:17:24');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (48, 'Bernette Rodger', 'brodger1b@sitemeter.com', 'Qal‘ah-ye Kuhnah', 'Afghanistan', '2026-08-06 00:07:10');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (49, 'Sampson Sutor', 'ssutor1c@irs.gov', 'Qal‘ah-ye Shāhī', 'Afghanistan', '2026-05-29 03:52:45');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (50, 'Rickey Shurman', 'rshurman1d@ibm.com', 'Andkhōy', 'Afghanistan', '2026-02-02 01:43:10');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (51, 'Geoff Penhall', 'gpenhall1e@nydailynews.com', 'Pas Pul', 'Afghanistan', '2026-08-06 02:40:40');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (52, 'Kath Birkett', 'kbirkett1f@berkeley.edu', 'Balkh', 'Afghanistan', '2026-02-16 14:09:46');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (53, 'Rhiamon Denton', 'rdenton1g@barnesandnoble.com', 'Qal‘ah-ye Shahr', 'Afghanistan', '2026-03-26 07:36:49');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (54, 'Verile Laughlan', 'vlaughlan1h@storify.com', 'Qarāwul', 'Afghanistan', '2026-09-07 11:46:28');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (55, 'Zoe Stiffkins', 'zstiffkins1i@answers.com', 'Uruzgān', 'Afghanistan', '2026-06-16 19:28:44');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (56, 'Jae Colgrave', 'jcolgrave1j@admin.ch', 'Chowṉêy', 'Afghanistan', '2025-11-15 09:09:56');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (57, 'Ibby Duckinfield', 'iduckinfield1k@exblog.jp', 'Cool űrhajó', 'Afghanistan', '2026-02-11 00:01:34');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (58, 'Berk Frapwell', 'bfrapwell1l@mediafire.com', 'Chakaray', 'Afghanistan', '2026-04-07 22:26:55');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (59, 'Neal Niset', 'nniset1m@nyu.edu', 'Bagrāmī', 'Afghanistan', '2026-04-08 12:25:25');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (60, 'Shawnee Towndrow', 'stowndrow1n@huffingtonpost.com', 'Panjāb', 'Afghanistan', '2026-01-12 17:51:54');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (61, 'Tasha Radbourn', 'tradbourn1o@imageshack.us', 'Zīrakī', 'Afghanistan', '2026-05-16 02:18:05');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (62, 'Audra De Vuyst', 'ade1p@e-recht24.de', 'Mehtar Lām', 'Afghanistan', '2026-04-30 15:30:59');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (63, 'Merrily Blenkensop', 'mblenkensop1q@google.co.uk', 'Bal Chirāgh', 'Afghanistan', '2026-07-21 12:16:14');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (64, 'Orella Kennedy', 'okennedy1r@dot.gov', 'Ghurayd Gharamē', 'Afghanistan', '2026-09-01 10:01:20');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (65, 'Esmaria Desaur', 'edesaur1s@dmoz.org', 'Cool űrhajó', 'Afghanistan', '2026-01-10 09:04:58');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (66, 'Field Backs', 'fbacks1t@foxnews.com', 'Mūsá Qal‘ah', 'Afghanistan', '2025-12-12 13:37:36');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (67, 'Eadie Alldre', 'ealldre1u@netscape.com', 'Khānaqāh', 'Afghanistan', '2026-02-17 07:38:52');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (68, 'Joleen Sayre', 'jsayre1v@mapquest.com', 'Pachīr wa Āgām', 'Afghanistan', '2025-12-10 01:43:20');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (69, 'Wendy Kenwyn', 'wkenwyn1w@bloglines.com', 'Sar-e Pul', 'Afghanistan', '2026-05-09 10:19:17');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (70, 'Remus Bastistini', 'rbastistini1x@apple.com', 'Khudāydād Khēl', 'Afghanistan', '2026-09-16 04:30:27');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (71, 'Celinka Scutts', 'cscutts1y@ehow.com', 'Taloqan', 'Afghanistan', '2025-12-17 09:18:06');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (72, 'Flint Oxbrow', 'foxbrow1z@timesonline.co.uk', 'Bal Chirāgh', 'Afghanistan', '2026-08-16 20:52:27');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (73, 'Idalina Urch', 'iurch20@phoca.cz', 'Chandal Bā’ī', 'Afghanistan', '2026-09-18 19:58:50');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (74, 'Donella Cattanach', 'dcattanach21@japanpost.jp', 'Khūgyāṉī', 'Afghanistan', '2026-02-11 13:26:47');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (75, 'Caron Goold', 'cgoold22@sogou.com', 'Ḩājī Khēl', 'Afghanistan', '2026-03-28 10:47:24');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (76, 'Devonna Shand', 'dshand23@scribd.com', 'Qal‘ah-ye Na‘īm', 'Afghanistan', '2026-06-12 01:53:29');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (77, 'Tadeo Buglar', 'tbuglar24@sohu.com', 'Khōshī', 'Afghanistan', '2026-04-26 10:51:46');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (78, 'Larisa Shutler', 'lshutler25@dailymotion.com', 'Sang-e Chārak', 'Afghanistan', '2026-01-15 05:41:43');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (79, 'Ruthi Ropkes', 'rropkes26@hhs.gov', 'Sar Chakān', 'Afghanistan', '2026-09-03 05:41:16');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (80, 'Humfrid Denniss', 'hdenniss27@e-recht24.de', 'Zaranj', 'Afghanistan', '2026-02-24 21:21:40');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (81, 'Dinnie Darnborough', 'ddarnborough28@bizjournals.com', 'Sangar Sarāy', 'Afghanistan', '2026-02-17 11:49:14');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (82, 'Nils Briggs', 'nbriggs29@eventbrite.com', 'Zargarān', 'Afghanistan', '2026-08-19 12:54:11');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (83, 'Stephen Ellingford', 'sellingford2a@ocn.ne.jp', 'Kabul', 'Afghanistan', '2025-12-04 08:58:37');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (84, 'Silvester Murricanes', 'smurricanes2b@dell.com', 'Now Zād', 'Afghanistan', '2026-08-04 13:54:57');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (85, 'Sophey Dellenbrook', 'sdellenbrook2c@technorati.com', 'Zerok-Alakadari', 'Afghanistan', '2026-01-15 03:02:14');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (86, 'Wendye Gherardini', 'wgherardini2d@craigslist.org', 'Khanabad', 'Afghanistan', '2026-09-20 23:09:40');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (87, 'Lev Biesinger', 'lbiesinger2e@ycombinator.com', 'Alah Sāy', 'Afghanistan', '2025-11-20 01:24:36');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (88, 'Humphrey Graysmark', 'hgraysmark2f@hexun.com', 'Mutā Khān', 'Afghanistan', '2026-09-05 02:46:48');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (89, 'Tobe Birchall', 'tbirchall2g@biblegateway.com', '‘Alāqahdārī Kirān wa Munjān', 'Afghanistan', '2026-07-20 20:02:33');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (90, 'Blakeley Zuann', 'bzuann2h@bloglovin.com', 'Chisht-e Sharīf', 'Afghanistan', '2026-02-05 12:10:58');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (91, 'Zacharia Killner', 'zkillner2i@fotki.com', 'Adraskan', 'Afghanistan', '2026-08-12 17:07:55');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (92, 'Lemmy Andri', 'landri2j@biblegateway.com', 'Aībak', 'Afghanistan', '2026-03-06 17:48:33');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (93, 'Barnett Tumbelty', 'btumbelty2k@mail.ru', 'Pul-e Khumrī', 'Afghanistan', '2026-06-25 18:01:19');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (94, 'Tammy Webben', 'twebben2l@google.co.uk', 'Khānaqāh', 'Afghanistan', '2026-07-02 09:38:48');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (95, 'Arte Kynton', 'akynton2m@nydailynews.com', 'Ḩājī Khēl', 'Afghanistan', '2026-01-13 00:16:18');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (96, 'Bard Ziemsen', 'bziemsen2n@purevolume.com', 'Alah Sāy', 'Afghanistan', '2025-11-23 15:47:38');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (97, 'Olia Fantin', 'ofantin2o@liveinternet.ru', 'Quchanghī', 'Afghanistan', '2025-11-12 14:19:31');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (98, 'Spencer Alsina', 'salsina2p@sphinn.com', 'Markaz-e Woluswalī-ye Āchīn', 'Afghanistan', '2026-03-24 00:31:19');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (99, 'Mina Gutman', 'mgutman2q@microsoft.com', 'Barakī Barak', 'Afghanistan', '2026-05-09 23:33:01');
insert into MOCK_DATA (id, name, email, city, country, created_at) values (100, 'Dalt Heffernan', 'dheffernan2r@prlog.org', 'Pul-e Sangī', 'Afghanistan', '2026-05-18 14:07:55');`

}

seed();
